language: python
dist: xenial

env:
  global:
    - COVERALLS_PARALLEL=true
  matrix:
    - TEST_FILE="tests/test_labeling/"
    - TEST_FILE="tests/test_classification/"
    - TEST_FILE="tests/test_embeddings/"
    - TEST_FILE="tests/test_corpus.py tests/test_utils.py"

python:
  - "3.6"

cache: pip

before_install:
  - export BOTO_CONFIG=/dev/null

stages:
  - Lint
  - Test

install:
  - pip install -r requirements.dev.txt
  - pip install -r requirements.txt
  - python -c "import kashgari;print(f'kashgari version {kashgari.__version__}')"
  - git fetch --unshallow --quiet
  - export PYTHONPATH=`pwd`

script: pytest --doctest-modules --junitxml=test-reports/junit.xml
  --cov=kashgari --cov-report=xml:coverage.xml --cov-report=html:htmlcov --cov-config .coveragerc
  $TEST_FILE

after_script:
  - coveralls

notifications:
  webhooks: https://coveralls.io/webhook

jobs:
  include:
    - stage: Lint
      python: "3.6"
      install:
        - pip install -r requirements.dev.txt
      script:
        - sh ./scripts/lint.sh
